# Generated by Django 4.0.6 on 2022-07-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_race', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Training date')),
                ('activity', models.CharField(choices=[('R', 'Run'), ('B', 'Bike'), ('S', 'Swim'), ('W', 'Weight'), ('C', 'Cross-Fit'), ('O', 'Other')], default='R', max_length=1, verbose_name='Activity')),
                ('distance', models.FloatField(verbose_name='distance - miles')),
                ('duration', models.FloatField(verbose_name='training duration')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.race')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='race',
            name='completed',
            field=models.ManyToManyField(to='main_app.completed'),
        ),
    ]
