# Generated by Django 4.0.6 on 2022-07-17 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_completed_alter_race_distance_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(1)]),
        ),
    ]
