# Generated by Django 4.0.6 on 2022-07-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_race_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='image',
            field=models.URLField(),
        ),
    ]
