# Generated by Django 4.0.6 on 2022-07-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_race_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.FloatField(),
        ),
    ]
